trigger:
- main

pool:
  name: Default

steps:
# Passo 1: Compilar o Back-end (.NET)
- script: |
    echo "A restaurar os pacotes e a compilar o .NET Core..."
    dotnet restore
    dotnet build --configuration Release
  workingDirectory: 'Controle De Gasto/back/ControleDeGasto'
  displayName: 'Compilar Back-end (.NET)'

# Passo 2: Compilar o Front-end (Angular)
- script: |
    echo "A instalar dependências e a compilar o Angular..."
    npm install
    npm run build
  workingDirectory: 'Controle De Gasto/frontControle'
  displayName: 'Compilar Front-end (Angular)'